1 - Crie um array Numpy 1D com 10 elementos e, em seguida, inverta a ordem dos elementos.

In [2]:
import numpy as np

In [92]:
# resolva o Exercício aqui
array = np.random.randint(0, 10, 10)
np.flip(array)

array([6, 1, 7, 4, 0, 9, 3, 1, 6, 9])

2 - Crie uma matriz 3x3 com números aleatórios entre 0 e 1.

In [32]:
# resolva o Exercício aqui
matriz = np.random.rand(3, 3)
matriz

array([[0.89052231, 0.53331254, 0.86443424],
       [0.85090396, 0.28375734, 0.39049983],
       [0.37389967, 0.26185973, 0.54328184]])

3 - Dado um array 1D, encontre os índices dos elementos que são maiores que 5.

In [33]:
# resolva o Exercício aqui
np.where(array > 5)

(array([0, 1, 4], dtype=int64),)

4 - Dada uma matriz 4x4, calcule a soma dos elementos de cada coluna e cada linha.

In [38]:
# resolva o Exercício aqui
matriz = np.random.rand(4, 4)
matriz.sum(axis = 1)

array([2.79859522, 2.90488857, 3.07367552, 1.8394154 ])

5 - Crie uma matriz identidade 5x5 usando Numpy.

In [47]:
# resolva o Exercício aqui
matriz = np.identity(5)
matriz

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6 - Dado um array 1D, substitua todos os números pares por -1 sem alterar o array original.

In [93]:
# resolva o Exercício aqui
array_ = array.copy()
array_[array_ % 2 == 0] = -1

print(array)
print(array_)

[9 6 1 3 9 0 4 7 1 6]
[ 9 -1  1  3  9 -1 -1  7  1 -1]


7 - Dadas duas matrizes, calcule a soma, a subtração, a multiplicação elemento a elemento e a multiplicação de matrizes.

In [ ]:
# resolva o Exercício aqui


8 - Implemente uma função que calcula a distância euclidiana entre dois vetores usando Numpy.

In [ ]:
# resolva o Exercício aqui


9 - Dado um array, encontre a média, a mediana e o desvio padrão dos elementos.

In [ ]:
# resolva o Exercício aqui


10 - Dada uma matriz, normalize-a de forma que seus elementos estejam no intervalo [0, 1].

In [ ]:
# resolva o Exercício aqui


11 - Dado um conjunto de pontos, calcule a matriz de distâncias euclidianas entre todos os pares de pontos.

In [ ]:
# resolva o Exercício aqui


12 - Implemente uma função que recebe um array e um valor e retorna o valor mais próximo do array.

In [ ]:
# resolva o Exercício aqui


13 - Crie um array 2D 8x8 com um padrão de tabuleiro de xadrez usando 0s e 1s.

In [ ]:
# resolva o Exercício aqui


14 - Implemente uma função que recebe um array e um valor e retorna o índice do elemento mais próximo do valor no array.

In [ ]:
# resolva o Exercício aqui


15 - Dado um array 1D, calcule a autocorrelação do array.

In [ ]:
# resolva o Exercício aqui


16 - Implemente uma função que retorna a matriz de covariância entre duas variáveis de entrada usando Numpy.

In [ ]:
# resolva o Exercício aqui


17 - Implemente uma função que calcula o produto interno entre dois vetores usando Numpy.

In [ ]:
# resolva o Exercício aqui


18 - Dado um array 1D, calcule a diferença entre os elementos consecutivos.

In [ ]:
# resolva o Exercício aqui


19 - Dada uma matriz, calcule a transposta e a inversa da matriz usando Numpy.

In [ ]:
# resolva o Exercício aqui


20 - Implemente uma função que recebe um array 1D e retorna um array com os elementos normalizados para que a soma dos elementos seja igual a 1 (distribuição de probabilidade).

In [ ]:
# resolva o Exercício aqui
